language: ruby

script: bundle exec rspec

gemfile:
  - gemfiles/rails_4.0.0.gemfile
  - gemfiles/rails_4.1.0.gemfile
  - gemfiles/rails_4.2.0.gemfile
  - gemfiles/rails_5.0.0.gemfile
  - gemfiles/rails_5.1.1.gemfile

rvm:
  - 2.3.0

matrix:
  include:
    - rvm: 3.1.2
      gemfile: gemfiles/rails_7.0.3.gemfile

before_install:
  - gem update bundler
